<!-- Copyright (c) 2026 Neil Colvin. MIT licensed. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../CrestronHomeDevTools/CrestronHomeDevTools.csproj" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="CrestronHomeNUnit.TestAdapter" Version="1.12.1" ExcludeAssets="build;buildTransitive" />
  </ItemGroup>
</Project>
