<!-- Copyright (c) 2026 Neil Colvin. Licensed under the MIT License. See LICENSE. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../CrestronHomeDevTools/CrestronHomeDevTools.csproj" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../CrestronHomeDevTools.Console/CrestronHomeDevTools.Console.csproj" /></ItemGroup>
</Project>
